# -*- coding: utf-8 -*-
"""Accuracy

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cRwy9084j69FM_gj9gFw7HH7IAnFLY8r
"""

# Evaluate the model's performance
val_loss, val_accuracy = final_model.evaluate(val_generator)
print(f'Validation Loss: {val_loss}')
print(f'Validation Accuracy: {val_accuracy}')

# Save the model in H5 format
final_model.save('maize_disease_detection_model.h5')

# Alternatively, save the model in TensorFlow's SavedModel format
final_model.save('maize_disease_detection_model')