# -*- coding: utf-8 -*-
"""Train Distributed Model

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cRwy9084j69FM_gj9gFw7HH7IAnFLY8r
"""

# Train the model with the distributed strategy
final_model.fit(
    train_generator,
    epochs=10,  # Set the number of epochs
    validation_data=val_generator
)

